"""Static constants for the Daily Learning App."""

# ──────────────────────────────────────────────
# Categories
# ──────────────────────────────────────────────

CATEGORIES: list[str] = [
    "Physics",
    "Biology",
    "Chemistry",
    "Mathematics",
    "Psychology",
    "Books",
    "Religion",
    "History",
    "Historic Figures",
    "Battles",
    "Sports",
    "Artificial Intelligence",
    "Machine Learning",
    "Coding",
    "Computer Science",
    "Science",
    "Technology",
    "Space",
    "Astronomy",
    "Geography",
    "Philosophy",
    "Economics",
    "Art",
    "Music",
    "Architecture",
    "Animals",
    "Nature",
    "Inventions",
    "Interesting Facts",
    "Mythology",
    "Languages",
]

# ──────────────────────────────────────────────
# Category → Wikipedia search queries
# Each category maps to a list of search terms
# that Wikipedia is likely to return good results
# for. The topic selector picks one deterministically.
# ──────────────────────────────────────────────

CATEGORY_QUERIES: dict[str, list[str]] = {
    "Physics": [
        "quantum mechanics", "general relativity", "thermodynamics",
        "electromagnetism", "nuclear physics", "particle physics",
        "optics", "fluid dynamics", "wave–particle duality",
        "Higgs boson", "dark matter", "string theory",
        "superconductivity", "Brownian motion", "photoelectric effect",
        "special relativity", "Newton's laws of motion", "entropy",
        "plasma physics", "Doppler effect",
    ],
    "Biology": [
        "DNA replication", "photosynthesis", "evolution",
        "cell biology", "genetics", "ecology",
        "microbiology", "neuroscience", "immunology",
        "mitosis", "CRISPR gene editing", "natural selection",
        "human anatomy", "virology", "marine biology",
        "enzymes", "biodiversity", "symbiosis",
        "epigenetics", "stem cell",
    ],
    "Chemistry": [
        "periodic table", "chemical bond", "organic chemistry",
        "electrochemistry", "polymer chemistry", "acid–base reaction",
        "catalysis", "thermochemistry", "biochemistry",
        "molecular orbital theory", "chemical equilibrium",
        "nuclear chemistry", "redox reaction", "crystallography",
        "stoichiometry", "solutions chemistry", "nanochemistry",
        "green chemistry", "chemical kinetics", "spectroscopy",
    ],
    "Mathematics": [
        "calculus", "linear algebra", "number theory",
        "probability theory", "topology", "game theory",
        "Fibonacci sequence", "prime number", "graph theory",
        "Fourier transform", "Euclidean geometry", "set theory",
        "Bayesian statistics", "chaos theory", "fractal",
        "cryptography mathematics", "differential equation",
        "complex analysis", "combinatorics", "Riemann hypothesis",
    ],
    "Psychology": [
        "cognitive psychology", "behavioral psychology", "Maslow's hierarchy of needs",
        "Stanford prison experiment", "cognitive dissonance", "classical conditioning",
        "Milgram experiment", "attachment theory", "Dunning–Kruger effect",
        "psychoanalysis", "positive psychology", "neuropsychology",
        "social psychology", "developmental psychology", "memory psychology",
        "confirmation bias", "placebo effect", "flow psychology",
        "emotional intelligence", "Gestalt psychology",
    ],
    "Books": [
        "War and Peace", "To Kill a Mockingbird", "1984 novel",
        "One Hundred Years of Solitude", "The Great Gatsby",
        "Don Quixote", "Pride and Prejudice", "The Odyssey",
        "Crime and Punishment", "Brave New World",
        "The Catcher in the Rye", "Moby-Dick", "Hamlet",
        "The Lord of the Rings", "Fahrenheit 451",
        "Les Misérables", "The Art of War", "Sapiens book",
        "Thinking, Fast and Slow", "A Brief History of Time",
    ],
    "Religion": [
        "Buddhism", "Christianity", "Islam",
        "Hinduism", "Judaism", "Sikhism",
        "Taoism", "Confucianism", "Zoroastrianism",
        "Jainism", "Shinto", "Ancient Greek religion",
        "Religious philosophy", "meditation", "monasticism",
        "pilgrimage", "religious texts", "Abrahamic religions",
        "karma", "enlightenment religion",
    ],
    "History": [
        "Industrial Revolution", "French Revolution", "Renaissance",
        "Cold War", "Ancient Egypt", "Roman Empire",
        "World War I", "World War II", "Age of Exploration",
        "American Revolution", "Ottoman Empire", "Silk Road",
        "Ancient Greece", "Byzantine Empire", "Meiji Restoration",
        "Mongol Empire", "Viking Age", "Reformation",
        "decolonization", "Space Race",
    ],
    "Historic Figures": [
        "Albert Einstein", "Leonardo da Vinci", "Marie Curie",
        "Nikola Tesla", "Mahatma Gandhi", "Nelson Mandela",
        "Isaac Newton", "Cleopatra", "Napoleon Bonaparte",
        "Alexander the Great", "Ada Lovelace", "Charles Darwin",
        "Genghis Khan", "Julius Caesar", "Alan Turing",
        "Galileo Galilei", "Martin Luther King Jr.", "Queen Victoria",
        "Confucius", "Aristotle",
    ],
    "Battles": [
        "Battle of Waterloo", "Battle of Thermopylae", "Battle of Stalingrad",
        "Battle of Gettysburg", "Battle of Hastings", "Battle of Midway",
        "Battle of Actium", "Battle of Agincourt", "Battle of the Bulge",
        "Siege of Constantinople", "Battle of Verdun", "Battle of Kursk",
        "Battle of Marathon", "Battle of Trafalgar", "D-Day Normandy landings",
        "Battle of Austerlitz", "Battle of Cannae", "Battle of Lepanto",
        "Battle of the Somme", "Battle of Gallipoli",
    ],
    "Movies": [
        "The Shawshank Redemption", "The Godfather", "Inception film",
        "Pulp Fiction", "Schindler's List", "The Matrix",
        "2001: A Space Odyssey", "Interstellar film", "Citizen Kane",
        "Blade Runner", "Parasite film", "Spirited Away",
        "The Dark Knight", "Casablanca film", "Vertigo film",
        "Apocalypse Now", "Fight Club film", "Amélie",
        "Seven Samurai", "There Will Be Blood",
    ],
    "Sports": [
        "FIFA World Cup", "Olympic Games", "cricket sport",
        "basketball", "tennis", "association football",
        "Formula One", "rugby football", "baseball",
        "marathon running", "swimming sport", "boxing",
        "gymnastics", "ice hockey", "golf",
        "Tour de France", "chess", "table tennis",
        "surfing", "mixed martial arts",
    ],
    "Artificial Intelligence": [
        "artificial neural network", "deep learning", "natural language processing",
        "computer vision", "reinforcement learning", "Turing test",
        "GPT language model", "artificial general intelligence",
        "machine perception", "expert system", "autonomous vehicle",
        "AI ethics", "speech recognition", "generative adversarial network",
        "transformer architecture", "backpropagation", "convolutional neural network",
        "robotics AI", "AI alignment", "artificial intelligence history",
    ],
    "Machine Learning": [
        "supervised learning", "unsupervised learning", "random forest",
        "support vector machine", "gradient descent", "decision tree learning",
        "k-nearest neighbors", "clustering analysis", "dimensionality reduction",
        "bias–variance tradeoff", "cross-validation statistics",
        "feature engineering", "ensemble learning", "Bayesian network",
        "recurrent neural network", "transfer learning",
        "overfitting", "regularization machine learning",
        "principal component analysis", "neural network training",
    ],
    "Coding": [
        "Python programming language", "JavaScript", "Rust programming language",
        "Go programming language", "TypeScript", "C programming language",
        "version control", "Git software", "open-source software",
        "algorithm", "data structure", "software design pattern",
        "object-oriented programming", "functional programming",
        "API", "web development", "software testing",
        "agile software development", "DevOps", "Linux",
    ],
    "Computer Science": [
        "algorithm complexity", "operating system", "compiler",
        "database", "computer network", "cryptography",
        "distributed computing", "automata theory", "computer architecture",
        "information theory", "Boolean algebra", "hash function",
        "binary search", "sorting algorithm", "graph algorithm",
        "Turing machine", "P versus NP problem",
        "parallel computing", "virtual memory", "TCP/IP",
    ],
    "Science": [
        "scientific method", "CERN", "Hubble Space Telescope",
        "periodic table of elements", "DNA structure", "black hole",
        "climate change science", "plate tectonics", "vaccine science",
        "nuclear fission", "supernova", "electromagnetic spectrum",
        "genetically modified organism", "stem cell research",
        "antimatter", "quantum computing", "bioluminescence",
        "geothermal energy", "nuclear fusion", "nanotechnology",
    ],
    "Technology": [
        "internet history", "World Wide Web", "semiconductor",
        "blockchain technology", "5G", "cloud computing",
        "cybersecurity", "Internet of Things", "3D printing",
        "virtual reality", "augmented reality", "GPS technology",
        "electric vehicle", "renewable energy technology", "quantum computer",
        "fiber optics", "drone technology", "biometrics",
        "lithium-ion battery", "satellite communication",
    ],
    "Space": [
        "black hole", "Mars planet", "International Space Station",
        "Milky Way", "exoplanet", "solar system",
        "neutron star", "space exploration", "Hubble Space Telescope",
        "James Webb Space Telescope", "Big Bang", "asteroid",
        "dwarf planet", "Saturn rings", "space station",
        "rocket propulsion", "SpaceX", "lunar exploration",
        "cosmic microwave background", "dark energy",
    ],
    "Astronomy": [
        "supernova", "galaxy formation", "stellar evolution",
        "pulsar", "quasar", "Andromeda Galaxy",
        "Kepler's laws of planetary motion", "Orion constellation",
        "Oort cloud", "Kuiper belt", "solar eclipse",
        "binary star", "red giant", "white dwarf star",
        "Hertzsprung–Russell diagram", "radio astronomy",
        "gravitational lensing", "celestial mechanics",
        "astronomical observatory", "Cepheid variable",
    ],
    "Geography": [
        "plate tectonics", "Amazon rainforest", "Sahara Desert",
        "Great Barrier Reef", "Mariana Trench", "Ring of Fire",
        "Himalaya", "Nile", "Grand Canyon",
        "Antarctica", "tundra", "volcanic island",
        "continental drift", "ocean current", "fjord",
        "coral reef", "monsoon", "permafrost",
        "Mediterranean Sea", "Mount Everest",
    ],
    "Philosophy": [
        "Socrates", "existentialism", "Stoicism",
        "utilitarianism", "Plato", "Immanuel Kant",
        "nihilism", "empiricism", "rationalism",
        "ethics philosophy", "epistemology", "metaphysics",
        "free will philosophy", "philosophy of mind",
        "social contract", "Friedrich Nietzsche",
        "phenomenology", "pragmatism philosophy",
        "categorical imperative", "thought experiment",
    ],
    "Economics": [
        "supply and demand", "inflation economics", "GDP",
        "stock market", "cryptocurrency", "Adam Smith",
        "Keynesian economics", "free market", "trade economics",
        "monetary policy", "fiscal policy", "economic bubble",
        "Great Depression", "microeconomics", "macroeconomics",
        "behavioral economics", "game theory economics",
        "globalization economics", "central bank", "economic inequality",
    ],
    "Art": [
        "Mona Lisa", "Renaissance art", "Impressionism",
        "Pablo Picasso", "Vincent van Gogh", "modern art",
        "Michelangelo", "Baroque art", "Surrealism",
        "art history", "sculpture", "abstract art",
        "Frida Kahlo", "Andy Warhol", "Cubism",
        "Japanese art", "calligraphy", "photography art",
        "street art", "Art Nouveau",
    ],
    "Music": [
        "classical music", "jazz", "rock music",
        "blues music", "hip hop music", "Ludwig van Beethoven",
        "Wolfgang Amadeus Mozart", "music theory", "electronic music",
        "opera", "symphony", "musical instrument",
        "reggae", "punk rock", "K-pop",
        "music production", "Baroque music", "soul music",
        "folk music", "music history",
    ],
    "Architecture": [
        "Gothic architecture", "Taj Mahal", "Eiffel Tower",
        "Frank Lloyd Wright", "Colosseum", "Parthenon",
        "Art Deco architecture", "Bauhaus", "skyscraper",
        "Great Wall of China", "Sagrada Família", "Pyramids of Giza",
        "dome architecture", "bridge engineering", "sustainable architecture",
        "ancient Roman architecture", "Islamic architecture",
        "modern architecture", "cathedral", "pagoda",
    ],
    "Animals": [
        "octopus", "dolphin", "elephant",
        "honey bee", "eagle", "wolf",
        "cheetah", "blue whale", "great white shark",
        "penguin", "gorilla", "butterfly",
        "chimpanzee", "orca", "rhinoceros",
        "coral reef ecosystem", "migration animal", "camouflage biology",
        "endangered species", "tardigrade",
    ],
    "Nature": [
        "aurora borealis", "volcano", "earthquake",
        "coral reef", "rainforest", "glacier",
        "tsunami", "hurricane", "fossil",
        "photosynthesis", "water cycle", "nitrogen cycle",
        "carbon cycle", "biodiversity", "ecosystem",
        "wildfire ecology", "desert ecology", "mangrove",
        "old-growth forest", "deep sea",
    ],
    "Inventions": [
        "printing press", "light bulb", "telephone",
        "steam engine", "penicillin", "internet invention",
        "television", "airplane", "telescope",
        "compass invention", "wheel invention", "dynamite",
        "vaccination", "transistor", "photography invention",
        "radio invention", "bicycle", "refrigerator",
        "microscope", "gunpowder",
    ],
    "Interesting Facts": [
        "Bermuda Triangle", "Voyager Golden Record", "Rosetta Stone",
        "Fermi paradox", "Dunbar's number", "Fibonacci in nature",
        "déjà vu", "synesthesia", "lucid dream",
        "Mpemba effect", "double-slit experiment", "Ship of Theseus",
        "Mandela effect", "Baader–Meinhof phenomenon", "overview effect",
        "Dunning–Kruger effect", "butterfly effect",
        "Sapir–Whorf hypothesis", "trolley problem", "Monty Hall problem",
    ],
    "Mythology": [
        "Greek mythology", "Norse mythology", "Egyptian mythology",
        "Roman mythology", "Hindu mythology", "Japanese mythology",
        "Celtic mythology", "Mesopotamian mythology",
        "Aztec mythology", "Chinese mythology",
        "Zeus", "Thor mythology", "Anubis",
        "Athena", "Loki mythology", "Medusa",
        "Hercules", "Odin", "Aphrodite",
        "Poseidon",
    ],
    "Languages": [
        "linguistics", "Indo-European languages", "Mandarin Chinese",
        "Arabic language", "sign language", "Rosetta Stone",
        "constructed language", "etymology", "phonetics",
        "sociolinguistics", "language family", "pidgin language",
        "writing system", "alphabet history", "Sanskrit",
        "endangered language", "bilingualism", "translation studies",
        "Braille", "cuneiform script",
    ],
}

# ──────────────────────────────────────────────
# Category groupings (for frontend display)
# ──────────────────────────────────────────────

CATEGORY_GROUPS: dict[str, list[str]] = {
    "Science": [
        "Physics", "Biology", "Chemistry", "Mathematics", "Science",
    ],
    "Technology": [
        "Artificial Intelligence", "Machine Learning", "Coding",
        "Computer Science", "Technology", "Inventions",
    ],
    "Space & Nature": [
        "Space", "Astronomy", "Geography", "Animals", "Nature",
    ],
    "History & Humanities": [
        "History", "Historic Figures", "Battles", "Philosophy",
        "Economics", "Religion", "Languages",
    ],
    "Culture & Arts": [
        "Books", "Movies", "Music", "Art", "Architecture",
        "Sports", "Mythology",
    ],
    "Mind & Life": [
        "Psychology", "Interesting Facts",
    ],
}
